spring:
  application:
    name: bkhtmltopdf
    version: @project.version@
  servlet:
    multipart:
      enabled: true
      max-file-size: 32MB
      max-request-size: 32MB

bkhtmltopdf:
  renderer:
    timeout: 15s
  controller:
    html-to-pdf:
      enabled: true
    fonts:
      enabled: true
    md-to-pdf:
      enabled: true
    pdf-to-jpg:
      enabled: true
  console:
    enabled: false

